### ISSUE TITLE
see also

### ISSUE THREAD

**Issue by chdlong** [rujews/maupassant-hugo#35]
hugo内置的see also算法，推荐时只推荐比本文章时间更早的文章，所以想改下配置，查看了hugo官方给出的配置方法是yml格式的，如下：
related:
  threshold: 80
  includeNewer: false
  toLower: false
  indices:
    - name: keywords
       weight: 100
     - name: date
       weight: 10
我们的主题配置使用的是toml格式，我尝试了好多种都不对，toml官方也没有这样的例子。
请问这几句配置怎么写成toml格式呢？
问题发布后缩进会变没有，我没法发图片， 我看到你在知乎上回答了我的问题，可惜也是因为缩进的问题，导致你看不清，我在知乎上修改成了图片，才显出了缩进，我觉得是indices:包含两项内容，每项是个结构体，我不会表示了，你要实在看不清，可以自己查下see also官方配置 @rujews

**Comment by rujews** [comment]
TOML的数组是要分开两个的，知乎上我也给了你例子。你这个要改成TOML的话，应该是这样。
```toml
[related]
threshold = 80.0
includeNewer = false
toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 100.0

  [[related.indices]]
  name = "date"
  weight = 10.0
```

@chdlong
