### ISSUE TITLE
添加友链三条及以上使得页面崩溃，无法点击

### ISSUE THREAD

**Issue by ketchuppp** [rujews/maupassant-hugo#71]
我尝试添加第三条友链后，会出现页面直接卡死，无法点击
```toml
[[params.links]]
  title = "abc"
  name = "abc"
  url = "https://abc.xyz/"

[[params.links]]
  title = "def"
  name = "def"
  url = "https://def.gitee.io/"
```
而一旦添加第三条就会使页面无响应，无法点击，F12同样无响应
